[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
monitor_speed = 115200
lib_deps = 
	blynkkk/Blynk
	adafruit/DHT sensor library @ ^1.4.7
	adafruit/Adafruit Unified Sensor @ ^1.1.15